[package]
name = "dyn_traits"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["dynamic", "derive"]
description = "Magically derive non-object-safe traits"
readme = "README.md"
repository = "https://github.com/shigma/dyn_derive"
